yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

handler404 = 'posts.views.page_not_found'  # noqa
handler500 = 'posts.views.server_error'  # noqa

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

yatube/templates/includes/class_a.html
<div class="card">
        <div class="card-body">
          <div class="h3">
              {{ author.get_full_name }}
          </div>
          <div class="h3 text-muted">
            @{{ author.username }}
          </div>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="h6 text-muted">
              Подписчиков: {{ author.following.count }} <br>
              Подписан: {{ author.follower.count }}
            </div>
          </li>
          <li class="list-group-item">
            <div class="h6 text-muted">
              <p> Записей:
              {{ author.posts.count }}
              </p>
            </div>
          </li>
        </ul>
</div>

yatube/templates/includes/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}
{% if form %}
  {% if user.is_authenticated %}
    <div class="card my-4">
      <form action="{% url 'add_comment' post.author.username post.id %}" method="post">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <form>
          <div class="form-group">
            {{ form.text|addclass:"form-control" }}
          </div>
          <button type="submit" class="btn btn-primary">Добавить коментарий</button>
            </form>
        </div>
      </form>
    </div>
  {% endif %}
{%  endif %}
<!-- Комментарии -->
{% for comment in comments %}
  <div class="media card mb-4">
    <div class="media-body card-body">
      <h5 class="mt-0">
        <a href="{% url 'profile' username=comment.author.username %}"
          name="comment_{{ comment.id }}"
        >{{ comment.author.username }}</a>
      </h5>
      <p>{{ comment.text|linebreaksbr }}</p>
      <small class="text-muted">{{ comment.created|date:"d E Y г. H:i" }}
      </small>
       {% if request.user == comment.post.author or request.user == comment.author %}
      <a class="btn btn-danger ml-1 mr-1"
         href="{% url 'comment_delete' id=comment.id %}"
         role="button">
        Удалить Комментарий
      </a>
      {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/footer.html
<!-- Шаблон footer.html -->
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">Об авторе  </a>
    <a href="{% url 'about:tech' %}"> Технологии</a>
  </p>
  <p class="m-0 text-dark text-center ">
    Социальная сеть <span style="color:red">Ya</span>tube © {{ year }}. все права защищены.
  </p>
    <p class="m-0 text-dark text-center "> Зарегистрированных пользователей:
     {{ user_count }}
</footer>

yatube/templates/includes/menu.html
{% if user.is_authenticated %}
  <div class="row">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'follow_index' %}">
          Избранные авторы
        </a>
      </li>
     <li class="nav-item">
        <a class="nav-link {% if group_list %}active{% endif %}" href="{% url 'group_list' %}">
          Сообщества
        </a>
      </li>
    </ul>
  </div>
{% endif %}

yatube/templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{% url 'index' %}"><span style="color:red">Ya</span>tube</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
        <div class="dropdown">
     <button class="btn btn dropdown-toggle" type="button" id="dropdownMenuButton"
             data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</button>
       <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="p-2 text-dark dropdown-item" href="{% url 'profile' user.username %}">{{ user.username }}</a>
      <a class="p-2 text-dark dropdown-item" href="{% url 'new_post' %}">Новая запись</a>
      <a class="p-2 text-dark dropdown-item" href="{% url 'password_change' %}">Изменить пароль</a>
       </div>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
    {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
      <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav>

yatube/templates/includes/paginator.html
{% if page.has_other_pages %}
  <nav>
    <ul class="pagination">
      {% if page.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">&laquo; Предыдущая</span>
        </li>
      {% endif %}
      {% for i in page.paginator.page_range %}
        {% if page.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}
              <span class="sr-only">(текущая)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page.has_next %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Следующая &raquo;</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/includes/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

  <!-- Отображение картинки -->
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}">
  {% endthumbnail %}
  <!-- Отображение текста поста -->
  <div class="card-body">
    <p class="card-text">
      <!-- Ссылка на автора через @ -->
      <a name="post_{{ post.id }}" href="{% url 'profile' post.author.username %}">
        <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
      </a>
      {{ post.text|linebreaksbr }}
    </p>

    <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
    {% if post.group %}
      <a class="card-link muted" href="{% url 'group' post.group.slug %}">
        <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
      </a>
    {% endif %}

    <!-- Отображение ссылки на комментарии -->

      <div class="mb-3 d-flex justify-content-between align-items-center">
        <!--  <a class="mr-3" href="{ url 'like_post' %}"><i class="fa fa-heart text-primary" aria-hidden="true"></i> { post.posts_liked }}</a>
  -->       {% if post.comments.exists %}
            Комментариев: {{ post.comments.count }}
         {% else %}
            Комментариев пока нет
         {% endif %}
            <a class="mr-3"><i class="fa fa-eye text-primary" aria-hidden="true"></i> {{ post.total_views }}</a>
      </div>
      <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        {% if not form %}
          <div>
        <a class="btn btn-sm btn-primary ml-2" href="{% url 'post' post.author.username post.id %}" role="button">
          Просмотр
        </a>
          </div>
        {% endif %}
        <!-- Ссылка на редактирование поста для автора -->
        {% if user == post.author %}
                    <div>

          <a class="btn btn-sm btn-info ml-2" href="{% url 'edit_post' post.author.username post.id %}" role="button">
            Редактировать/
            удалить
          </a>
          </div>
        {% endif %}

     </div>
      <!-- Дата публикации поста -->
      <small class="text-muted">{{ post.pub_date|date:"d E Y" }} г.</small>
    </div>
  </div>
</div>

yatube/templates/includes/subscribe.html
<li class="list-group-item">
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'profile_unfollow' author.username %}" role="button">
      Отписаться
    </a>
  {% else %}
    <a
      class="btn btn-lg btn-primary"
      href="{% url 'profile_follow' author.username  %}" role="button">
      Подписаться
    </a>
  {% endif %}
</li>